PATH_TO_PANEL_FRIENDS = "div>div>div>div>div:nth-of-type(3)>div>div>div>div>div>div>div:nth-of-type(4)>div>div>div>div>div>div>div>div>div"
PATH_TO_FRIEND = "div>div>div>div>div:nth-of-type(3)>div>div>div>div>div>div>div:nth-of-type(4)>div>div>div>div>div>div>div>div>div:nth-of-type(3)>div"
PATH_TO_COUNT_FRIENDS = "(//a[@role='menuitemradio'])[1]/div/div/div/span/span[2]"
PATH_TO_BUTTON_FRIENS = "(//a[@role='menuitemradio'])[1]"
PATH_TO_MYPROFILE = "html>body>div>div>div>div>div:nth-of-type(2)>div:nth-of-type(4)>div>div:nth-of-type(4)>a"
PATH_TO_DROP_DOWN_FORM = "//div[@role='tab']"
SELECTOR_FOR_LOGIN = "email"
SELECTOR_FOR_PASSWD = "pass"
SELECTOR_FOR_BUTTON = "button"
PATH_ADDRESS_IN_PROFILE = "div > div > a"
PATH_FULLNAME = "div > div > a > span"
